---
stages:
  - syntax
  - unit
  - acceptance-puppet6
  - acceptance-puppet7
  - release

cache:
  paths:
    - vendor/bundle

before_script:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem --version
  - bundle -v
  - bundle install --without system_tests --path vendor/bundle --jobs $(nproc)

syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop-Ruby 2.7.5-Puppet ~> 7.9:
  stage: syntax
  image: ruby:2.7.5
  script:
    - bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
  variables:
    PUPPET_GEM_VERSION: '~> 7.9'

parallel_spec-Ruby 2.7.5-Puppet ~> 7.9:
  stage: unit
  image: ruby:2.7.5
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 7.9'

acceptance with puppet6:
  stage: acceptance-puppet6
  variables:
    PUPPET_INSTALL_TYPE: 'agent'
    BEAKER_IS_PE: 'no'
    BEAKER_PUPPET_COLLECTION: 'puppet6'
    BEAKER_debug: 'true '
    RBENV_VERSION: '2.7.5'
  script:
    - bundle exec rake spec_prep beaker:default
  tags:
    - puppet-tests
  except:
    - master

acceptance with puppet7:
  stage: acceptance-puppet7
  variables:
    PUPPET_INSTALL_TYPE: 'agent'
    BEAKER_IS_PE: 'no'
    BEAKER_PUPPET_COLLECTION: 'puppet7'
    BEAKER_debug: 'true '
    RBENV_VERSION: '2.7.5'
  script:
    - bundle exec rake spec_prep beaker:default
  tags:
    - puppet-tests
  except:
    - master

module release:
  stage: release
  variables:
    RBENV_VERSION: '2.7.5'
  script:
    - rm -f Gemfile.lock
    - bundle exec pdk build
  tags:
    - puppet-tests
  only:
    - tags
  except:
    - branches
  artifacts:
    paths:
      - pkg/
    expire_in: 6 weeks
