---
.yardopts:
  delete: true
.travis.yml:
  delete: true
appveyor.yml:
  delete: true
.gitignore:
  paths:
    - .devcontainer/
    - .vscode/
    - .yardopts
.gitlab-ci.yml:
  unmanaged: true

Gemfile:
  required:
    ':development':
      - gem: 'hiera'
      - gem: 'rspec-puppet'
      - gem: 'beaker'
      - gem: 'beaker-puppet'
      - gem: 'beaker-rspec'
      - gem: 'ed25519'
      - gem: 'bcrypt_pbkdf'
      - gem: 'beaker-puppet_install_helper'
      - gem: 'beaker-module_install_helper'
      - gem: 'beaker-vagrant'
      - gem: 'bolt'
      - gem: 'pdk'
        version: '3.2.0'

Rakefile:
  requires:
    - 'beaker-rspec/rake_task'
 
spec/spec_helper.rb:
  mock_with: ':rspec'
