---
HOSTS:
  ipa-server-1:
    roles:
    - default
    - master
    - centos
    platform: el-9-x86_64
    hypervisor: vagrant
    box: eurolinux-vagrant/centos-stream-9
    box_version: 9.0.45
    box_check_update: false
    vagrant_memsize: 2048
    vagrant_cpus: 2
  ipa-server-2:
    roles:
    - replica
    - centos
    platform: el-9-x86_64
    hypervisor: vagrant
    box: eurolinux-vagrant/centos-stream-9
    box_version: 9.0.45
    box_check_update: false
    vagrant_memsize: 2048
    vagrant_cpus: 2
  ipa-client:
    roles:
    - client
    platform: el-9-x86_64
    hypervisor: vagrant
    box: eurolinux-vagrant/centos-stream-9
    box_version: 9.0.45
    box_check_update: false
    vagrant_memsize: 1024

CONFIG:
  type: foss
  loglevel: debug
